WebApi: DB_Object Class Reference
DB_Object Class Reference
Public Member Functions
getName ()
getId ()
getInfo ($obj, $name)
putInfo ($obj, $property, $value)
addChild ($child)
addChildren ($children)
getPassKey ()
checkPassword ($new, $original=false)
changePassword ($new)
isAllowed ($classname, $action, $property)
updateFromDatabase ($column, $value)
updateToDatabase ()
Static Public Member Functions
static hashPassword ($password, $iterations=1)
Protected Member Functions
__construct (&$db, &$config, $column, $value, $profile=array(), $new=false)
changePasshash ($new)
getTable ()
Protected Attributes
$info = array()
$protect = true
$clienthashing = false
$table
Static Protected Attributes
static $enableprotect = true
static $parent = true
Detailed Description
Definition at line 38 of file Object.php.
Constructor & Destructor Documentation
DB_Object::__construct (&$ db, &$ config, $ column, $ value, $ profile = array(), $ new = false) [protected]
Store the database and given information within the object. If an empty password is given then password protection is disabled. If the $curpass variable is empty then client hashing will be disabled.
Parameters:
object &$db A DB_Database object used for database queries
int $id The ID of the object
string $name The name of the object (e.g. username for users)
string $origpass A SHA512 hash of the original password protecting the object
string $curpass The current one-time key produced by hash chaining
int $curpassnum The number of hash iterations for the $curpass
array $profile Any information specific to the object from the database
Definition at line 96 of file Object.php.
References $config, $info, getTable(), hashPassword(), MAIN_Logger::NOTICE, updateFromDatabase(), updateToDatabase(), and MAIN_Error::WARNING.
Member Function Documentation
DB_Object::addChild ($ child)
Merges a child database object with the current object.
Adds an array with the child object's ID, name, profile, and the object itself into the current object's profile. It is stored in: $<currentObject>->profile[<nameOfChildObject>][]
Parameters:
object $child Child object to store
Returns:
bool True on success, false otherwise
Definition at line 218 of file Object.php.
Referenced by addChildren().
DB_Object::addChildren ($ children)
Merges multiple child database objects with the current object. Calls the addChild function for each child given.
Parameters:
array $child Child objects to add
Returns:
bool True on success, false otherwise
Definition at line 243 of file Object.php.
References addChild().
DB_Object::changePasshash ($ new) [protected]
Used for one time keys when hash chaining and client-side hashing is enabled. Decreases the hash chain count by one and uses the given hash as the new current hash.
Parameters:
string $new The next hash in the hash chain (as supplied by the user)
Returns:
bool True on success, false on failure
Definition at line 329 of file Object.php.
References $info.
Referenced by checkPassword().
DB_Object::changePassword ($ new)
Change the password for the object.
Store a new password hash in the database as well as the password hashed 1000 times for client side hashing.
Parameters:
string $new The new plaintext password
Returns:
bool True on success, false on failure.
Definition at line 304 of file Object.php.
References hashPassword(), and updateToDatabase().
DB_Object::checkPassword ($ new, $ original = false)
Compare a given password to the stored password hash.
Parameters:
string $new The password to check
bool $original Whether the given password is the actual plaintext password or a one time key on the hash chain
Returns:
bool True if the password is correct, false otherwise
Definition at line 273 of file Object.php.
References changePasshash(), and hashPassword().
DB_Object::getId ()
Get the ID of the object.
Returns:
int The ID of the object
Definition at line 145 of file Object.php.
DB_Object::getInfo ($ obj, $ name)
Get any property of an object, checking if the object is allowed to access the property first.
The permission to get the value of any property is in the form of "$classname-get-$name", where $classname is the name of this object, and $name is the property being accessed. However, if the object has: * "*-get-$name" (get $name from any object), * "$classname-*-$name" (do anything to $name for this class), * "$classname-get-*" (get anything from the object) or any combination of those, the request will also be allowed.
Parameters:
object $obj A copy of the calling object (just give $this)
string $name Name of the property to access
Returns:
mixed The requested property if allowed, MAIN_Error if not allowed
Definition at line 166 of file Object.php.
References MAIN_Error::WARNING.
DB_Object::getName ()
Get the name of the object.
Returns:
string The name of the object
Definition at line 136 of file Object.php.
DB_Object::getPassKey ()
Get the current iteration on the hash chain.
Returns:
array The current iteration on the hash chain
Definition at line 257 of file Object.php.
DB_Object::getTable () [protected]
Gets the table associated with this object, and sets it up if it does not exist.
First checks if the table already exists, and returns it if it does. If not, constructs SQL to create a new table using definitions in the configuration file, then submits the query, reloads the database, and tries to get the table again.
Returns:
object DB_Table on success, MAIN_Error on error
Definition at line 431 of file Object.php.
References $table, and MAIN_Error::ERROR.
Referenced by __construct(), updateFromDatabase(), and updateToDatabase().
static DB_Object::hashPassword ($ password, $ iterations = 1) [static]
Hash a given plaintext password a given number of times (1 hash is the default).
Parameters:
string $password The password to hash
int $iterations Number of times to hash the password
Returns:
string Hash of the password
Definition at line 495 of file Object.php.
Referenced by __construct(), changePassword(), and checkPassword().
DB_Object::isAllowed ($ classname, $ action, $ property)
Check if the object is allowed to do a certain action.
Checks the groups of the object, and uses MAIN_Config to compile an array of permissions from those groups. Then checks if the $action is in the array.
The format of a permission is "$classname-$action-$property", where $classname is the object being accessed, $action is either 'get' or 'set', and $property is the name of the property. By having that permission, the action is allowed. In addition, the asterisk wildcard can be used in any field to give permission for any class, any action, any property, or a combination of the three.
Parameters:
string $action Requested action
Returns:
bool True if allowed, false otherwise
Definition at line 359 of file Object.php.
DB_Object::putInfo ($ obj, $ property, $ value)
Set any property of an object, checking if the object is allowed to access the property first.
The permission to set the value of any property is in the form of "$classname-set-$name", where $classname is the name of this object, and $name is the property being accessed. However, if the object has: * "*-set-$name" (get $name from any object), * "$classname-*-$name" (do anything to $name for this class), * "$classname-set-*" (get anything from the object) or any combination of those, the request will also be allowed.
Parameters:
object $obj A copy of the calling object (just give $this)
string $name Name of the property to give a new value
string $value Value to give the property
Returns:
mixed The requested property if allowed, MAIN_Error if not allowed
Definition at line 195 of file Object.php.
References MAIN_Error::WARNING.
DB_Object::updateFromDatabase ($ column, $ value)
Get properties about the object from the database.
Parameters:
string $column Column to search for info from.
string $value Value in the column to match the object to.
Definition at line 396 of file Object.php.
References $table, and getTable().
Referenced by __construct().
DB_Object::updateToDatabase ()
Update properties about the object to the database.
Returns:
bool True on success, false on failure.
Definition at line 411 of file Object.php.
References $table, and getTable().
Referenced by __construct(), and changePassword().
Member Data Documentation
DB_Object::$clienthashing = false [protected]
Whether to enable client hashing, when a password is entered by a user, hash chaining is used on the client side to prevent man-in-the-middle attacks. Requires the proper client-side scripts to be in place.
Definition at line 75 of file Object.php.
DB_Object::$enableprotect = true [static, protected]
Determines whether to enable password protection on a global scope. Should be customized in the child class definition.
Definition at line 46 of file Object.php.
DB_Object::$info = array() [protected]
Stores information about the object that has been retrieved from the database.
Definition at line 61 of file Object.php.
Referenced by __construct(), and changePasshash().
DB_Object::$parent = true [static, protected]
Determines whether the object can take in other objects as its children. When taking in a child object, the profiles of the two are merged.
Definition at line 54 of file Object.php.
DB_Object::$protect = true [protected]
Determines whether to enable password protection on a per-object basis.
Definition at line 67 of file Object.php.
DB_Object::$table [protected]
A DB_Table object to be used for all database queries.
Definition at line 81 of file Object.php.
Referenced by getTable(), updateFromDatabase(), and updateToDatabase().
The documentation for this class was generated from the following file:
app/db/Object.php