.TH "API" 3 "28 Jan 2010" "Version 0.2" "WebApi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
API \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Interacts with a MySQL or Mssql database to store and retrieve information.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Interacts with a MySQL or Mssql database to store and retrieve information for a defined object, such as a user object. Classes should inherit this class in order to become a Database object.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Interacts with a MySQL table to store and retrieve information.
.PP
Creates a number of abstract functions to allow easy database queries as well as automatic escaping of given values.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Handles local caching of HTML for requests that do not change often.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Stores configuration option, usually taken from a file.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Main class for handling web requests, and redirecting jobs to the database and request classes.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Stores error information when an error occurs in a Database object. Automatically logs the error using a \fBMAIN_Logger\fP object.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Logs important information generated by the script. Intended mainly for logging database queries executed by other objects in this namespace.
.PP
The format for the log entries is '$time ($pid - $id) : $level [$callback] - $message', where $time is the time, $pid is the process ID, $id is a unique ID created at the beginning of the script, $level is the error type, $callback is the function that triggered the error, and $message is the actual error.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Takes configuration options from a controller for a web request, then passes the options to a template, printing HTML to the client if applicable.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Holds session and request information, including the $_GET, $_SERVER, $_SERVER, and $_SESSION variables.
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved)
.RE
.PP
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the \fBDB_Object\fP class to make models and the \fBOUT_Request\fP class to make controllers. HTML is stored in templates with special tags. See the \fBOUT_Template\fP class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
.PP
Copyright (C) 2009 Tyler Romeo
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. Loads an HTML template from a local file, and replaces specific tags with the given values.
.PP
Tags take the following form: <!options[[tagname]]> replacing options with a comma separated list of options and tagname with the name of the tag.
.PP
For options, each option is delimited by a comma, and requires an option name. If '=' and then a value is placed after the option name, the value following the equals sign is assigned as the option value. Valid options are: * array=separator - The value given to the template will be an array. Implode the array using the given separator. * switch - If set, instead of using the value in the template, determine which of two static values to use, either the switch_true option if $value is true, or the switch_false option if false. * noescape - Do not escape HTML characters in the value * trim=4 - Trim the value to the given number of characters * padding=2 - Pad the value to the given number of characters * padvalue=
.br
 - Use the given value to pad the value rather than spaces * template - Instead of inserting data from the database, it inserts another template
.PP
\fBAuthor:\fP
.RS 4
Tyler Romeo <tylerromeo@gmail.com>  http://opensource.org/licenses/gpl-3.0.html GNU General Public License 3.0  Copyright (c) 2009, Tyler Romeo (Some Rights Reserved) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for WebApi from the source code.
