.TH "app/main/Autoloader.php" 3 "9 Feb 2010" "Version 0.2" "WebApi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/Autoloader.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMAIN_Autoloader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__autoload\fP ($classname)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__autoload ($ classname)"
.PP
Definition at line 81 of file Autoloader.php.
.PP
References MAIN_Autoloader::getInstance().
.SH "Author"
.PP 
Generated automatically by Doxygen for WebApi from the source code.
