.TH "index.php" 3 "28 Jan 2010" "Version 0.2" "WebApi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAPI\fP "
.br
.ti -1c
.RI "enum \fBID\fP "
.br
.ti -1c
.RI "enum \fBROOTDIR\fP "
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$config\fP = new \fBMAIN_Config\fP()"
.br
.ti -1c
.RI "foreach(scandir(ROOTDIR. '/plugins') as $filename) \fB$controller\fP = new \fBMAIN_Controller\fP()"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAPI\fP"
.PP
Definition at line 4 of file index.php.
.SS "enum \fBID\fP"
.PP
Definition at line 5 of file index.php.
.SS "enum \fBROOTDIR\fP"
.PP
Definition at line 6 of file index.php.
.SH "Variable Documentation"
.PP 
.SS "$config = new \fBMAIN_Config\fP()"
.PP
Definition at line 13 of file index.php.
.PP
Referenced by DB_Object::__construct().
.SS "foreach (scandir(ROOTDIR. '/plugins') as $filename) $controller = new \fBMAIN_Controller\fP()"
.PP
Definition at line 27 of file index.php.
.SH "Author"
.PP 
Generated automatically by Doxygen for WebApi from the source code.
