WebApi: MAIN_Cache Class Reference
MAIN_Cache Class Reference
Public Member Functions
__construct (&$config, &$session)
canBeCached ($action)
cacheExpired ()
storeCache ($output)
getCache ()
Private Member Functions
getCacheFilename ()
Private Attributes
$config
$session
Detailed Description
Definition at line 37 of file Cache.php.
Constructor & Destructor Documentation
MAIN_Cache::__construct (&$ config, &$ session)
Stores the controller and configuration objects.
Parameters:
object &$config MAIN_Config object
object &$controller MAIN_Controller object
Definition at line 57 of file Cache.php.
References $config, $session, and MAIN_Error::ERROR.
Member Function Documentation
MAIN_Cache::cacheExpired ()
Determines whether the cache for this specific request has expired or not.
Returns:
True if it has or if it has never been cached
Definition at line 87 of file Cache.php.
References getCacheFilename().
MAIN_Cache::canBeCached ($ action)
Determines whether a given action can be locally cached.
Parameters:
string $action The action of the request
Returns:
bool True if it can, false otherwise
Definition at line 75 of file Cache.php.
MAIN_Cache::getCache ()
Retrieves the cache for the current request, and returns it with a special footer.
Returns:
string|bool False on error, the cache otherwise
Definition at line 122 of file Cache.php.
References getCacheFilename().
MAIN_Cache::getCacheFilename () [private]
Determine the filename for the local cache of a specific request. Filename is simply the full URI including GET variables.
Returns:
string Valid filename
Definition at line 138 of file Cache.php.
Referenced by cacheExpired(), getCache(), and storeCache().
MAIN_Cache::storeCache ($ output)
Stores the current request in a cache file. Writes the given HTML to a local filename for fast access later.
Parameters:
string $output HTML to be cached
Returns:
bool True on success, false on error
Definition at line 106 of file Cache.php.
References getCacheFilename().
Member Data Documentation
MAIN_Cache::$config [private]
Stores a valid MAIN_Config class.
Definition at line 43 of file Cache.php.
Referenced by __construct().
MAIN_Cache::$session [private]
Stores a valid OUT_Session class.
Definition at line 49 of file Cache.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
app/main/Cache.php