WebApi: MAIN_Config Class Reference
MAIN_Config Class Reference
Public Member Functions
getOption ($option)
putOption ($option, $value)
insertPlugin ($name, $filename)
updateFromFile ($filename, $name= '')
updateToFile ($filename)
Private Attributes
$options = array()
Detailed Description
Definition at line 36 of file Config.php.
Member Function Documentation
MAIN_Config::getOption ($ option)
Get a configuration option.
Parameters:
string $option Name of the option
Returns:
mixed Option value, false if non-existent
Definition at line 51 of file Config.php.
MAIN_Config::insertPlugin ($ name, $ filename)
Helper function to insert plugins. Inserts the options of the given plugin configuration filename under the plugin_$name key in the global configuration.
Parameters:
string $name Base name for the plugin
string $filename Full filename for the config file
Returns:
bool True on success, false on failure
Definition at line 80 of file Config.php.
References updateFromFile().
MAIN_Config::putOption ($ option, $ value)
Stores a configuration option.
Parameters:
string $option Name of the option
string $value Value of the option
Returns:
bool True on success, false otherwise
Definition at line 63 of file Config.php.
MAIN_Config::updateFromFile ($ filename, $ name = '')
Load configuration options from a file, where each option has its own new line, and the option name is separated from the value with an '='.
Parameters:
string $filename Path to the configuration file
Returns:
bool True on success, false on failure
Definition at line 93 of file Config.php.
References $options, and MAIN_Error::ERROR.
Referenced by insertPlugin().
MAIN_Config::updateToFile ($ filename)
Update a configuration file with the local configuration options.
Parameters:
string $filename Path to the configuration file
Returns:
bool True on success, false on failure
Definition at line 118 of file Config.php.
References MAIN_Error::ERROR.
Member Data Documentation
MAIN_Config::$options = array() [private]
Configuration options
Definition at line 42 of file Config.php.
Referenced by updateFromFile().
The documentation for this class was generated from the following file:
app/main/Config.php