WebApi: OUT_Session Class Reference
OUT_Session Class Reference
Public Member Functions
__construct ()
startSession ()
endSession ()
getIpAddress ()
putSessionVal ($name, $value)
getVal ($name, $from= 'GET', $default=false)
getText ($name, $from= 'GET', $default= '')
getInt ($name, $from= 'GET', $default=0)
getFloat ($name, $from= 'GET', $default=0.0)
getBool ($name, $from= 'GET', $default=false)
Private Attributes
$SessionID
$VerifyID
$POST
$GET
$SERVER
Detailed Description
Definition at line 37 of file Session.php.
Constructor & Destructor Documentation
OUT_Session::__construct ()
Stores local copies of the POST, GET, and SERVER superglobals.
Definition at line 72 of file Session.php.
Member Function Documentation
OUT_Session::endSession ()
Ends a session by deleting the session cookie, destroying the session, and resetting the $_SESSION superglobal.
Definition at line 110 of file Session.php.
OUT_Session::getBool ($ name, $ from = 'GET', $ default = false)
Gets a boolean from either the $_GET, $_POST, $_SERVER, or $_SESSION superglobal. If $_GET is specified, the function will automatically search $_POST as well. Variables will automatically be cast as true or false.
Parameters:
string $name Name of the variable to retrieve
mixed $default What to return if the variable does not exist
string $from Superglobal to look from
Returns:
bool Variable if it exists, $default otherwise
Definition at line 219 of file Session.php.
References getVal().
OUT_Session::getFloat ($ name, $ from = 'GET', $ default = 0.0)
Gets a float from either the $_GET, $_POST, $_SERVER, or $_SESSION superglobal. If $_GET is specified, the function will automatically search $_POST as well. Variables will automatically be cast as floats.
Parameters:
string $name Name of the variable to retrieve
mixed $default What to return if the variable does not exist
string $from Superglobal to look from
Returns:
float Variable if it exists, $default otherwise
Definition at line 204 of file Session.php.
References getVal().
OUT_Session::getInt ($ name, $ from = 'GET', $ default = 0)
Gets a integer from either the $_GET, $_POST, $_SERVER, or $_SESSION superglobal. If $_GET is specified, the function will automatically search $_POST as well. Variables will automatically be cast as integers.
Parameters:
string $name Name of the variable to retrieve
mixed $default What to return if the variable does not exist
string $from Superglobal to look from
Returns:
int Variable if it exists, $default otherwise
Definition at line 189 of file Session.php.
References getVal().
OUT_Session::getIpAddress ()
Definition at line 118 of file Session.php.
References getText().
Referenced by startSession().
OUT_Session::getText ($ name, $ from = 'GET', $ default = '')
Gets a string from either the $_GET, $_POST, $_SERVER, or $_SESSION superglobal. If $_GET is specified, the function will automatically search $_POST as well. Variables will automatically be cast as strings.
Parameters:
string $name Name of the variable to retrieve
mixed $default What to return if the variable does not exist
string $from Superglobal to look from
Returns:
string Variable if it exists, $default otherwise
Definition at line 174 of file Session.php.
References getVal().
Referenced by getIpAddress(), and startSession().
OUT_Session::getVal ($ name, $ from = 'GET', $ default = false)
Gets a variable from either the $_GET, $_POST, $_SERVER, or $_SESSION superglobal. If $_GET is specified, the function will automatically search $_POST as well.
Parameters:
string $name Name of the variable to retrieve
string $from Superglobal to look from
mixed $default What to return if the variable does not exist
Returns:
mixed Variable if it exists, $default otherwise
Definition at line 149 of file Session.php.
Referenced by getBool(), getFloat(), getInt(), and getText().
OUT_Session::putSessionVal ($ name, $ value)
Stores a session variable.
Parameters:
string $name Name of the variable
string $value Value of the variable
Definition at line 134 of file Session.php.
Referenced by startSession().
OUT_Session::startSession ()
Starts a PHP session, stores the session id, and generates an unique hash using the IP address and the User Agent.
Definition at line 83 of file Session.php.
References getIpAddress(), getText(), and putSessionVal().
Member Data Documentation
OUT_Session::$GET [private]
The $_GET superglobal.
Definition at line 61 of file Session.php.
OUT_Session::$POST [private]
The $_POST superglobal.
Definition at line 55 of file Session.php.
OUT_Session::$SERVER [private]
The $_SERVER superglobal.
Definition at line 67 of file Session.php.
OUT_Session::$SessionID [private]
Session ID for the request.
Definition at line 43 of file Session.php.
OUT_Session::$VerifyID [private]
Verification hash to prevent session hijacking.
Definition at line 49 of file Session.php.
The documentation for this class was generated from the following file:
app/out/Session.php