WebApi: MAIN_Autoloader Class Reference
MAIN_Autoloader Class Reference
Public Member Functions
loadClass ($classname)
Static Public Member Functions
static loadFile ($filename)
static getInstance ($rootdir= '')
Private Member Functions
__construct ($rootdir)
Private Attributes
$rootdir
$loaded = array()
$classlist
Static Private Attributes
static $instance
Detailed Description
This program was created to make a set of classes to be used for easy website creation. Usage: simply extend the DB_Object class to make models and the OUT_Request class to make controllers. HTML is stored in templates with special tags. See the OUT_Template class for more details. Made by Tyler Romeo <tylerromeo@gmail.com>
Copyright (C) 2009 Tyler Romeo
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Definition at line 28 of file Autoloader.php.
Constructor & Destructor Documentation
MAIN_Autoloader::__construct ($ rootdir) [private]
Definition at line 49 of file Autoloader.php.
References $rootdir.
Member Function Documentation
static MAIN_Autoloader::getInstance ($ rootdir = '') [static]
Definition at line 74 of file Autoloader.php.
References $rootdir.
Referenced by __autoload().
MAIN_Autoloader::loadClass ($ classname)
Definition at line 55 of file Autoloader.php.
References loadFile().
static MAIN_Autoloader::loadFile ($ filename) [static]
Definition at line 65 of file Autoloader.php.
Referenced by loadClass().
Member Data Documentation
MAIN_Autoloader::$classlist [private]
Initial value:
 array(
                        'MAIN_Controller' => '/app/main/Controller.php',
                        'MAIN_Cache'      => '/app/main/Cache.php',
                        'MAIN_Config'     => '/app/main/Config.php',
                        'MAIN_Error'      => '/app/main/Error.php',
                        'MAIN_Logger'     => '/app/main/Logger.php',
                        'DB_Database'     => '/app/db/Database.php',
                        'DB_Object'       => '/app/db/Object.php',
                        'DB_Table'        => '/app/db/Table.php',
                        'OUT_Request'     => '/app/out/Request.php',
                        'OUT_Session'     => '/app/out/Session.php',
                        'OUT_Template'    => '/app/out/Template.php' )
Definition at line 34 of file Autoloader.php.
MAIN_Autoloader::$instance [static, private]
Definition at line 30 of file Autoloader.php.
MAIN_Autoloader::$loaded = array() [private]
Definition at line 33 of file Autoloader.php.
MAIN_Autoloader::$rootdir [private]
Definition at line 32 of file Autoloader.php.
Referenced by __construct(), and getInstance().
The documentation for this class was generated from the following file:
app/main/Autoloader.php