WebApi: DB_Table Class Reference
DB_Table Class Reference
Public Member Functions
__construct (&$database, $tablename)
& getLog ()
query ($sql)
result ($res, $type="array")
escape ($var)
select ($fields= '*', $where= '', $conditional= 'AND', $options=array())
insert ($row, $options=array())
update ($row, $where= '', $conditional= 'AND', $options=array())
delete ($where=array(), $conditional= 'AND', $options=array())
columns ()
Private Member Functions
whereStatement ($where, $conditional)
optionsStatement ($options)
Private Attributes
$database
$tablename
Detailed Description
Definition at line 40 of file Table.php.
Constructor & Destructor Documentation
DB_Table::__construct (&$ database, $ tablename)
Stores the database and table information.
Parameters:
object &$database Parent DB_Database object to use
string $tablename Name of the table to use
Definition at line 60 of file Table.php.
References $database, $tablename, and MAIN_Error::ERROR.
Member Function Documentation
DB_Table::columns ()
Returns an associative array of the columns for the table.
Returns:
array Columns and their descriptions
Definition at line 257 of file Table.php.
References query(), and result().
DB_Table::delete ($ where = array(), $ conditional = 'AND', $ options = array())
Deletes information from a table.
The equivalent of a DELETE query, which is created from the parameters and submitted to the database.
Parameters:
array $where Where to select information from
string $conditional The conditional to put in between the WHERE statements
array $options Other options to add to the query
Returns:
bool Returns true on success, false on failure
Definition at line 242 of file Table.php.
References optionsStatement(), query(), and whereStatement().
DB_Table::escape ($ var)
Escapes strings and arrays for use in a database query.
If a string is given, it is escaped using the parent object's function. If an array is given, all keys and values are escaped using the same method.
Parameters:
mixed $var The variable to escape
mixed The escaped variable
Definition at line 119 of file Table.php.
Referenced by insert(), optionsStatement(), select(), update(), and whereStatement().
& DB_Table::getLog ()
Get the log object for the database.
Returns:
object MAIN_Logger instance
Definition at line 76 of file Table.php.
DB_Table::insert ($ row, $ options = array())
Inserts a row into the database.
The equivalent of an INSERT query, which is created from the parameters and submitted to the database.
Parameters:
array $row The columns and values to add
array $options Other options to add to the query
Returns:
bool Returns true on success, false on failure
Definition at line 177 of file Table.php.
References escape(), optionsStatement(), query(), and MAIN_Error::WARNING.
DB_Table::optionsStatement ($ options) [private]
Takes a user-given array of extra query options and sticks them together for use in a query.
Parameters:
array $options The database options
Returns:
string Returns a valid list of options
Definition at line 298 of file Table.php.
References escape().
Referenced by delete(), insert(), select(), and update().
DB_Table::query ($ sql)
Queries the database by using the parent object's function.
Parameters:
string $sql Query to be submitted
Returns:
bool|resource Returns true or false for INSERT, DELETE, and other related queries. Returns a result resource for SELECT queries.
Definition at line 89 of file Table.php.
Referenced by columns(), delete(), insert(), select(), and update().
DB_Table::result ($ res, $ type = "array")
Obtains a result set from a result resource by using the parent object's function.
Parameters:
resource $res Result resource to get data from
string $type The function to use to get the data
mixed By default returns an array, but may change depending on the $type.
Definition at line 104 of file Table.php.
Referenced by columns().
DB_Table::select ($ fields = '*', $ where = '', $ conditional = 'AND', $ options = array())
Selects information from a table.
The equivalent of a SELECT query, which is created from the parameters and submitted to the database.
Parameters:
string|array $fields The fields to select as an array or string
array $where Where to select information from
string $conditional The conditional to put in between the WHERE statements
array $options Other options to add to the query
Returns:
resource Returns a result resource to get query information
Definition at line 150 of file Table.php.
References escape(), optionsStatement(), query(), and whereStatement().
DB_Table::update ($ row, $ where = '', $ conditional = 'AND', $ options = array())
Updates information in a table.
The equivalent of an UPDATE query, which is created from the parameters and submitted to the database.
Parameters:
array $row The columns and values to be updated
array $where Where to select information from
string $conditional The conditional to put in between the WHERE statements
array $options Other options to add to the query
Returns:
bool Returns true on success, false on failure
Definition at line 209 of file Table.php.
References escape(), optionsStatement(), query(), MAIN_Error::WARNING, and whereStatement().
DB_Table::whereStatement ($ where, $ conditional) [private]
Takes a user-given array of information and makes a SQL WHERE statement.
Parameters:
array $where Where to select information from
string $conditional The conditional to put in between the WHERE statements
Returns:
string Returns a valid WHERE statement
Definition at line 270 of file Table.php.
References escape().
Referenced by delete(), select(), and update().
Member Data Documentation
DB_Table::$database [private]
The parent DB_Database object
Definition at line 46 of file Table.php.
Referenced by __construct().
DB_Table::$tablename [private]
The name of the table in use
Definition at line 52 of file Table.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
app/db/Table.php