WebApi: DB_Database Class Reference
DB_Database Class Reference
Public Member Functions
__construct ($server, $username, $password, $database, &$log, $type= 'mysql')
connect ()
close ()
query ($sql)
result ($res, $type="array")
escape ($string)
getTable ($tablename)
& getLog ()
Static Public Attributes
static $globalfunctions
static $instance
Private Attributes
$conn = false
$conndata
$dbname
$functions
$tables
$log
Detailed Description
Definition at line 37 of file Database.php.
Constructor & Destructor Documentation
DB_Database::__construct ($ server, $ username, $ password, $ database, &$ log, $ type = 'mysql')
Stores connection data and attempts to connect.
The database type is given in the parameters. For MySQL and extensions with similar function calls can be built into the class. Otherwise, child classes will be automatically created if they exist.
Parameters:
string $server Server address to connect to
string $username Username for the server
string $password Password for the server
string $database Database name to connect to
object &$log MAIN_Logger object
string $type Name of database type
Returns:
bool|object Returns false if connection fails, returns object otherwise
Definition at line 125 of file Database.php.
References $log, connect(), and MAIN_Error::ERROR.
Member Function Documentation
DB_Database::close ()
Checks if a database connection is open, and if so shuts the connection.
Returns:
bool Returns true for success, false for failure
Definition at line 215 of file Database.php.
References MAIN_Error::ERROR, MAIN_Logger::INFO, and MAIN_Error::NOTICE.
Referenced by connect().
DB_Database::connect ()
Connects to a database server, e.g. MySQL, and stores the connection.
Returns:
bool Returns true for success, false for failure
Definition at line 158 of file Database.php.
References close(), MAIN_Error::ERROR, MAIN_Logger::INFO, query(), result(), and MAIN_Error::WARNING.
Referenced by __construct().
DB_Database::escape ($ string)
Escapes a string for use in a database query.
Parameters:
string $string The string to escape
Returns:
bool|string Returns the escaped string, or false on failure.
Definition at line 297 of file Database.php.
References MAIN_Error::ERROR, and MAIN_Error::WARNING.
& DB_Database::getLog ()
Get the log object for the database.
Returns:
object MAIN_Logger instance
Definition at line 339 of file Database.php.
DB_Database::getTable ($ tablename)
Get a table object for query usage.
Retrive an object for a specific table, rather than using the general query function.
Parameters:
string $tablename Name of the table
Returns:
object|bool Returns Table object, or false if table does not exist
Definition at line 321 of file Database.php.
References MAIN_Logger::INFO, and MAIN_Error::WARNING.
DB_Database::query ($ sql)
Submits a query to the database server, then returns the result of the query function.
Parameters:
string $sql A SQL query to submit
Returns:
bool|resource Returns true or false for INSERT, DELETE, and other related queries. Returns a result resource for SELECT queries.
Definition at line 243 of file Database.php.
References MAIN_Error::ERROR, MAIN_Logger::INFO, and MAIN_Error::WARNING.
Referenced by connect().
DB_Database::result ($ res, $ type = "array")
Obtains a result set from a result resource.
Parameters:
resource $res Result resource to get data from
string $type The function to use to get the data
array Array of all the rows retrieved
Definition at line 272 of file Database.php.
References MAIN_Error::ERROR, and MAIN_Error::WARNING.
Referenced by connect().
Member Data Documentation
DB_Database::$conn = false [private]
Stores resource for database connection.
Definition at line 74 of file Database.php.
DB_Database::$conndata [private]
Stores connection data for database, i.e. server, username, and password.
Definition at line 81 of file Database.php.
DB_Database::$dbname [private]
Stores the database name to connect to.
Definition at line 87 of file Database.php.
DB_Database::$functions [private]
Stores the functions to interact with the database. Usually loaded from one of the static variables.
Definition at line 95 of file Database.php.
DB_Database::$globalfunctions [static]
Initial value:
 array( "mysql" => array(
                                                "connect" => "mysql_connect",
                                                "close"   => "mysql_close",
                                                "db"      => "mysql_select_db",
                                                "query"   => "mysql_query",
                                                "result"  => "mysql_result",
                                                "array"   => "mysql_fetch_array",
                                                "assoc"   => "mysql_fetch_assoc",
                                                "escape"  => "mysql_real_escape_string",
                                                "numrows" => "mysql_num_rows" ),
                                         "mssql" => array(
                                                "connect" => "mssql_connect",
                                                "close"   => "mssql_close",
                                                "db"      => "mssql_select_db",
                                                "query"   => "mssql_query",
                                                "result"  => "mssql_result",
                                                "array"   => "mssql_fetch_array",
                                                "escape"  => "addslashes" )
                                 )
Array of database functions to be used in object.
Definition at line 44 of file Database.php.
DB_Database::$instance [static]
Stores singleton instance of object.
Definition at line 68 of file Database.php.
DB_Database::$log [private]
Stores a MAIN_Logger object.
Definition at line 107 of file Database.php.
Referenced by __construct().
DB_Database::$tables [private]
Stores table objects.
Definition at line 101 of file Database.php.
The documentation for this class was generated from the following file:
app/db/Database.php